### ISSUE TITLE
TAP crate

### ISSUE THREAD

**Issue by JuniorJPDJ** [meh/rust-tun#3]
I've seen you are going to do also TAP crate.
Does it have any ETA?

I would like to use it.

**Comment by meh** [comment]
I don't have any ETA on it, I wanted to make a common `netif` crate so that you could use some common stuff to set addresses and deal with network interfaces but it turned out to be harder than expected to do that.

If I were to just copypaste the code I have here to work with TAP interfaces then it would kind of work, but then there would be no common trait for the two, which is kind of subpar. I'd also like to get more platforms supported before moving onto TAP interfaces since TUN ones seem to be simpler to deal with.

**Comment by canndrew** [comment]
Would you accept PRs to add TAP functionality to this crate? I've been using this crate and I like, but now I need to move to using TAP.

**Comment by meh** [comment]
#14
